"""HTTP API to expose the TPRM research agent."""
from datetime import datetime
from typing import Any, Dict

from fastapi import FastAPI, HTTPException, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from agent.graph import run_graph


class ResearchRequest(BaseModel):
    company: str = Field(..., min_length=2, description="Official company name to research")


class ResearchResponse(BaseModel):
    company: str
    completed_at: str
    profile: Dict[str, Any]


app = FastAPI(
    title="TPRM Research API",
    description="POST company names to fetch the TPRM profile generated by the scraping agent.",
    version="1.0.0",
)


@app.get("/health")
def health_check():
    return {"status": "ok", "timestamp": datetime.utcnow().isoformat() + "Z"}


@app.post("/research", response_model=ResearchResponse)
def research_company(request: ResearchRequest):
    """Research a company using the agent and return the profile as JSON."""
    try:
        result = run_graph(request.company)
    except Exception as exc:  # pragma: no cover
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Research workflow failed: {exc}",
        )

    profile = result.get("company_profile")
    if not profile:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="The agent did not return a company profile.",
        )

    return ResearchResponse(
        company=request.company,
        completed_at=datetime.utcnow().isoformat() + "Z",
        profile=profile,
    )


@app.exception_handler(HTTPException)
def http_exception_handler(request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})
